# Generated by Django 3.2 on 2021-04-23 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Fashion', 'Fashion'), ('Nature', 'Nature'), ('Food', 'Food'), ('Travel', 'Travel'), ('Music', 'Music'), ('Lifestyle', 'Lifestyle'), ('Fitness', 'Fitness'), ('DIY', 'DIY'), ('Sports', 'Sports'), ('Finance', 'Finance'), ('Political', 'Political'), ('Parenting', 'Parenting'), ('Business', 'Business'), ('Personal', 'Personal'), ('Movie', 'Movie'), ('Automobile', 'Automobile'), ('News', 'News'), ('Pet', 'Pet'), ('Gaming', 'Gaming'), ('Other', 'Other')], max_length=50)),
                ('content', models.TextField()),
                ('references', models.CharField(blank=True, max_length=500, null=True)),
                ('image', smartfields.fields.ImageField(blank=True, default='default/Other.jpg', null=True, upload_to='blogImage/')),
                ('likes', models.ManyToManyField(related_name='blogpost_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Blog',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('picture', smartfields.fields.ImageField(blank=True, default='default/Profile.png', null=True, upload_to='profile/')),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('github', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Author',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
